volumes:
  gif-db: {}
services:
  app:
    environment:
      CUSTOM_MESSAGE: Add some gifs! :D
      MONGO_CONFIG_FILE: /sample/location/mongo-config.json
    image: node:16-alpine
    command: npm run dev
    working_dir: /usr/local/app
    volumes:
      - ./:/usr/local/app
      - ./mongo-config-sample.json:/sample/location/mongo-config.json
    ports:
      - 3000:3000
  mongo:
    image: mongo:5.0
    volumes:
      - gif-db:/data/db
  interface:
    image: mongo-express:latest
    ports:
      - 8080:8081