volumes:
  gif-db: {}
version: "3.8"
services:
  app:
    image: lnnguyen02/gif-collection
    ports:
      - 3000:3000
  mongo:
    image: mongo:5.0
    volumes:
      - gif-db:/data/db
  interface:
    image: mongo-express:latest
    ports:
      - 8080:8081